//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public string passportserial { get; set; }
        public string passportnumber { get; set; }
        public string postcode { get; set; }
        public string address { get; set; }
        public string addresslife { get; set; }
        public string company { get; set; }
        public string jobname { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
    }
}
