//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public string Active { get; set; }
        public string Expire { get; set; }
        public string Paused { get; set; }
        public string Withdrawn { get; set; }
        public int ID { get; set; }
    }
}
